getwd()
library(tm)
library(wordcloud)
library(RTextTools)
text<-readLines(file.choose())
docs<-Corpus(VectorSource(text))
docs<-tm_map(docs,tolower)
docs<-tm_map(docs,removeWords,stopwords("english"))
docs<-tm_map(docs,removeNumbers)
docs<-tm_map(docs,removePunctuation)
docs<-tm_map(docs,stripWhitespace)
docs<-tm_map(docs,stemDocument)
dts<-TermDocumentMatrix(docs)
m<-as.matrix(dts  a)
v<-sort(rowSums(m),decreasing = TRUE)
d<-data.frame(word=names(v),freq=v)
head(d,10)
wordcloud(d$word,freq = d$freq,min.freq = 1,max.words = 40,random.order = FALSE,rot.per =.1,color = brewer.pal(8,"Dark2"))